### ISSUE TITLE
[BUG]error message with reverse transformation in 'cellfinder_cell_standard'

### ISSUE THREAD

**Issue by zhiwen10** [SainsburyWellcomeCentre/cellfinder#108]
Hi Adam,
I'm trying to reverse transform simulated electrode track coordinates to atlas space, with 'cellfinder_cell_standard' command on windows 10. Amap registration was successful previously. 190917_488_hor_coronal_10um.nii (raw images), downsampled.nii and simulated_track.xml is provided in the [link](https://drive.google.com/drive/folders/1FLTv3RZkF2wqGa7E83rJwQs0h9iPH6uw?usp=sharing). Could you take a look if I did something noticeably wrong again?

Command:
`(cellfinder) E:\idisco\PV_0007>cellfinder_cell_standard --cells "E:/idisco/PV_0007/190917_488_hor_11-37-36_amap/simulated_track.xml" --transformation "E:/idisco/PV_0007/190917_488_hor_11-37-36_amap/registration/control_point_file.nii" --ref "E:/idisco/PV_0007/190917_488_hor_11-37-36_amap/registration/donwsampled.nii" -o "E:/idisco/PV_0007/190917_488_hor_11-37-36_amap/registration/" -x 0.01 -y 0.01 -z 0.01`

Error message appeared:
```
2020-05-10 00:51:35.875226: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "e:\miniconda3\envs\cellfinder\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\miniconda3\envs\cellfinder\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\miniconda3\envs\cellfinder\Scripts\cellfinder_cell_standard.exe\__main__.py", line 7, in <module>
  File "e:\miniconda3\envs\cellfinder\lib\site-packages\cellfinder\standard_space\cells_to_standard_space.py", line 213, in main
    tools.start_logging(
AttributeError: module 'cellfinder.tools.tools' has no attribute 'start_logging'
```

**Comment by adamltyson** [comment]
Hi Zhiwen,

Nothing to do with you. This is a tool that I didn't think anyone used, so I forgot to change when I refactored some code.  I should be able to fix it soon.

A couple of questions if you don't mind:
* How well did the idisco registration go? I haven't played with it much, but it wasn't amazing last time I tried.
* I'm assuming that you want to e.g. put neuropixels probe tracts into standard space, and then maybe analyse [like this](https://github.com/SainsburyWellcomeCentre/neuro/issues/13), and visualise a bit like this (although these are large optical fibres):
![probes](https://user-images.githubusercontent.com/13147259/81494394-8c085380-92a0-11ea-8093-dc15f63a873e.png)

I ask because this is a specific application I want to support with a GUI, so that you don't have to mess around with sticking together different tools. Is this something you'd be interested in?

**Comment by zhiwen10** [comment]
It will be great if you can fix this soon. Keep me updated.

- I only registered one iDisco sample right now. I think it's reasonably fine for most areas. There are some edges around RSP surface not aligned in this one, and hypothalamus is a little off. It could be the problem of this sample as well. Also, I would expect registration be worse than serial 2P in my case technically. It only took us 5-10 minutes to image this first whole brain with lightsheet of 5um resolution, some pixels can be out of focus.

- Yes, that is my intention. I would like to automatically assign each site on Neuropixels to a brain area. It would be cool to have GUI for all this. I have not tried brainrender yet. It looks really nice.

**Comment by adamltyson** [comment]
I've made a quick fix for this, so it should work. Also note the [updated documentation](https://sainsburywellcomecentre.github.io/cellfinder/main/user_guide/tools/cells_standard_space.html) (the only change is that the voxel spacing that the points are defined in should now be entered in um, rather than mm). N.B. This tool will be removed at some point, in favour of a more specialised tool.

You can get the updated version with `pip install cellfinder==0.3.13rc2`, let me know if there any issues.

It worked for me with:
```
cellfinder_cell_standard --cells /media/adam/Storage/cellfinder/data/zhiwen_track/simulated_track.xml --transformation /media/adam/Storage/cellfinder/data/zhiwen_track/control_point_file.nii --ref /media/adam/Storage/cellfinder/data/zhiwen_track/downsample.nii -o /media/adam/Storage/cellfinder/data/zhiwen_track/registration_cli_test -x 10 -y 10 -z 10
```

**Raw track**
![raw](https://user-images.githubusercontent.com/13147259/81496288-844fab80-92ae-11ea-9ee6-04d171f203e0.gif)


**Registered track**
![registered](https://user-images.githubusercontent.com/13147259/81496292-887bc900-92ae-11ea-9e94-caf00bf05e95.gif)

>Yes, that is my intention. I would like to automatically assign each site on Neuropixels to a brain area. It would be cool to have GUI for all this. 

For this, would you mind raising an issue detailing exactly what would be useful?

**Comment by zhiwen10** [comment]
Looking good. Thanks. Think there is still some windows system specific error.

`(cellfinder) C:\Users\Steinmetz lab>cellfinder_cell_standard --cells "E:/idisco/PV_0007/190917_488_hor_11-37-36_amap/simulated_track.xml" --transformation "E:/idisco/PV_0007/190917_488_hor_11-37-36_amap/registration/control_point_file.nii" --ref "E:/idisco/PV_0007/190917_488_hor_11-37-36_amap/registration/downsampled.nii" -o "E:/idisco/PV_0007/190917_488_hor_11-37-36_amap/test/" -x 10 -y 10 -z 10`

Error:

```
2020-05-10 03:31:55.727953: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-05-10 03:31:57 AM - INFO - MainProcess fancylog.py:265 - Starting logging
2020-05-10 03:31:57 AM - INFO - MainProcess fancylog.py:267 - Multiprocessing-logging module found. Logging from all processes
2020-05-10 03:31:57 AM - INFO - MainProcess cells_to_standard_space.py:229 - Starting transformation of cell positions
2020-05-10 03:31:57 AM - INFO - MainProcess cells_to_standard_space.py:126 - Generating deformation field
2020-05-10 03:32:53 AM - INFO - MainProcess cells_to_standard_space.py:55 - Loading deformation field
pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
2020-05-10 03:32:53 AM - INFO - MainProcess batteryrunners.py:274 - pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
2020-05-10 03:32:53 AM - INFO - MainProcess cells_to_standard_space.py:60 - Transforming cell positions
2020-05-10 03:32:53 AM - WARNING - MainProcess cells.py:325 - 0 cells were not transformed to standard space
2020-05-10 03:32:53 AM - INFO - MainProcess cells_to_standard_space.py:65 - Saving transformed cell positions
Traceback (most recent call last):
2020-05-10 03:32:53 AM - INFO - MainProcess cells_to_standard_space.py:74 - Removing standard space transformation temp files
  File "e:\miniconda3\envs\cellfinder\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\miniconda3\envs\cellfinder\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\miniconda3\envs\cellfinder\Scripts\cellfinder_cell_standard.exe\__main__.py", line 7, in <module>
  File "e:\miniconda3\envs\cellfinder\lib\site-packages\cellfinder\standard_space\cells_to_standard_space.py", line 230, in main
    transform_cells_to_standard_space(args)
  File "e:\miniconda3\envs\cellfinder\lib\site-packages\cellfinder\standard_space\cells_to_standard_space.py", line 75, in transform_cells_to_standard_space
    delete_temp(args.paths.standard_space_output_folder, args.paths)
  File "e:\miniconda3\envs\cellfinder\lib\site-packages\imlib\general\system.py", line 325, in delete_temp
    os.remove(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'E:/idisco/PV_0007/190917_488_hor_11-37-36_amap/test/deformation_field.nii'
```

**Comment by adamltyson** [comment]
Can you try using the `--debug` flag?

**Comment by zhiwen10** [comment]
With --debug flag, it worked. Hopefully, the more specialized tool in the future will contain such functionality to transform coordinate lists as well, as it's really useful in general.

**Comment by zhiwen10** [comment]
@adamltyson 
Question: is the reverse transformation truly reversible? If we transform the points on the probe in Atlas space (bended points in your second pic above) back to sample space with same transformation parameter, will be points be in line again, or not?

**Comment by adamltyson** [comment]
You can truly invert the linear part of the transformation, but the non-linear part is an approximation (although a good one) generated by an additional registration in the opposite direction.

I've tested this stuff before though, and it's very close (but not exact).

**Comment by zhiwen10** [comment]
Ok, the reverse transformation is just another registration in the opposite direction (sample to atlas), instead of using the inverse of the parameters of the first registration(atlas to sample). Do I understand this correctly?

**Comment by adamltyson** [comment]
It’s a bit of both.  The full transform is linear (affine transform) then non-linear. To invert the full transform, we invert the affine transform and then rerun the non-linear part (in the opposite direction).

**Comment by adamltyson** [comment]
Closing. See https://github.com/SainsburyWellcomeCentre/cellfinder/issues/110 for the windows issue
