### ISSUE TITLE
[BUG] cellfinder_view error: ModuleNotFoundError: No module named 'napari.qt'

### ISSUE THREAD

**Issue by rdbcasillas** [SainsburyWellcomeCentre/cellfinder#115]
**Describe the bug**
When I run "cellfinder_view", it throws an error: 

```
ModuleNotFoundError: No module named 'napari.qt'
```

**To Reproduce**
Please enter full details of how to reproduce this bug.

Opens a new window

**Log file**
```
(cellfinder) C:\Users\7057mehrav>cellfinder_view
Traceback (most recent call last):
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\7057mehrav\AppData\Local\Continuum\anaconda3\envs\cellfinder\Scripts\cellfinder_view.exe\__main__.py", line 4, in <module>
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder\lib\site-packages\neuro\visualise\viewer.py", line 23, in <module>
    from neuro.visualise.napari_tools.callbacks import display_brain_region_name
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder\lib\site-packages\neuro\visualise\napari_tools\callbacks.py", line 3, in <module>
    from napari.qt.threading import thread_worker
ModuleNotFoundError: No module named 'napari.qt'
```

**Desktop (please complete the following information):**
 - Windows 10

I have updated cellfinder and made sure that napari and pyside2 are installed.

**Comment by chrytsi** [comment]
I had the same error. Updating and explicitly installing the required dependencies didn't help either. 
So I removed the virtual environment, created a new one, re-installed cellfinder from scratch and now it's all good. :)

**Comment by adamltyson** [comment]
As above, if you’ve updated cellfinder, could you try a fresh conda environment?

**Comment by rdbcasillas** [comment]
Thanks @chrytsi , that worked! But I am now noticing that I am getting an error when clicking on the "load registration" button. I used to be able to pass this same folder as an argument (the older method on the docs that has been replaced) and it used to correctly show me annotated regions.  Attached is the screenshot with error. 


![image](https://user-images.githubusercontent.com/9725334/84573668-8df19500-adbf-11ea-80dd-7a70d914b98a.png)

**Comment by rdbcasillas** [comment]
Should have added the error  from console after clicking registration: 

```

(cellfinder2) C:\Users\7057mehrav>cellfinder_view
settings: screenshots are set to have transparent backgroundset the parameter "SCREENSHOT_TRANSPARENT_BACKGROUND" to false if you would prefer a not transparent background
WARNING: Empty filename passed to function
WARNING: Traceback (most recent call last):
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\neuro\visualise\viewer.py", line 276, in load_registration
    self.structures_df = load_structures_as_df(get_structures_path())
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\imlib\source\source_files.py", line 29, in get_structures_path
    atlas_conf = config_obj["atlas"]
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'atlas'
WARNING:vispy:Traceback (most recent call last):
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\neuro\visualise\viewer.py", line 276, in load_registration
    self.structures_df = load_structures_as_df(get_structures_path())
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\imlib\source\source_files.py", line 29, in get_structures_path
    atlas_conf = config_obj["atlas"]
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'atlas'

```

**Comment by adamltyson** [comment]
I think this is an existing bug, did you run `amap_download` before running `cellfinder view?

**Comment by adamltyson** [comment]
Sorry the docs for this workaround aren't clear, and this should be fixed.

**Comment by rdbcasillas** [comment]
hi @adamltyson ,

No, I didn't because i already did the registration before and I did do amap_download before that. But after starting a new conda environment and reinstalling cellfinder,  I didn't do amap_download. 

Attached is the snapshot of the output folder: 

![image](https://user-images.githubusercontent.com/9725334/84574021-a4005500-adc1-11ea-8558-f1e469d5d233.png)

Do i need to run amap_download command again? And does the old command for visualization still work (in which you passed amap's output folder as first parameter)?

**Comment by adamltyson** [comment]
Yes, can you run `amap_download` again? It shouldn't download anything, just update a config file.

Sorry, the old `amap_vis` command has been removed, cellfinder is still early in development, and so there will often be breaking changes. It is untested, but `pip install neuro==0.0.12` should get you the old versions of the viewers. 

However, if the new viewers don't work for you, please raise an issue and I will fix stuff or add new features.

**Comment by adamltyson** [comment]
Linking [the amap issue](https://github.com/SainsburyWellcomeCentre/amap-python/issues/60) that should prevent these issues long term.

**Comment by rdbcasillas** [comment]
thanks. I ran amap_download and it said this: 

```
(cellfinder2) C:\Users\7057mehrav>amap_download
Complete atlas already exists at C:\Users\7057mehrav\.amap\atlas. Skipping download
install: C:\Users\7057mehrav\.amap
Ensuring custom config file is correct
```

The amap output folder (that I was trying to open) is in Z: drive but my current location is C drive. Do I need to run amap_download from the Z drive?

**Comment by rdbcasillas** [comment]
Nevermind, it worked. thank you! I will close this now.
