### ISSUE TITLE
[BUG] Cell detection fails on Windows

### ISSUE THREAD

**Issue by adamltyson** [SainsburyWellcomeCentre/cellfinder#41]
Cell detection on windows fails with:

```python
C:\Users\adam.GARFIELD-WIN\.conda\envs\cellfinder\python.exe C:/Users/adam.GARFIELD-WIN/projects/cellfinder/cellfinder/main.py -s C:\Users\adam.GARFIELD-WIN\data\cellfinder\CT_BY_70_2_stitched\stitched\ch00 -b C:\Users\adam.GARFIELD-WIN\data\cellfinder\CT_BY_70_2_stitched\stitched\ch01 -o C:\Users\adam.GARFIELD-WIN\data\output\cellfindertest2 -x 2 -y 2 -z 5 --start-plane 1288 --end-plane 1305
2020-02-11 13:25:14 PM - INFO - MainProcess fancylog.py:265 - Starting logging
2020-02-11 13:25:14 PM - INFO - MainProcess fancylog.py:267 - Multiprocessing-logging module found. Logging from all processes
2020-02-11 13:25:14 PM - INFO - MainProcess main.py:64 - Skipping registration
2020-02-11 13:25:14 PM - INFO - MainProcess main.py:110 - Detecting cell candidates
Processing planes:   0%|          | 0/17 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:/Users/adam.GARFIELD-WIN/projects/cellfinder/cellfinder/main.py", line 158, in <module>
    main()
  File "C:/Users/adam.GARFIELD-WIN/projects/cellfinder/cellfinder/main.py", line 91, in main
    run_all(args, what_to_run)
  File "C:/Users/adam.GARFIELD-WIN/projects/cellfinder/cellfinder/main.py", line 112, in run_all
    detect.main(args)
  File "C:\Users\adam.GARFIELD-WIN\projects\cellfinder\cellfinder\detect\detect.py", line 114, in main
    bf_process.start()  # needs to be started before the loop
  File "C:\Users\adam.GARFIELD-WIN\.conda\envs\cellfinder\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\adam.GARFIELD-WIN\.conda\envs\cellfinder\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\adam.GARFIELD-WIN\.conda\envs\cellfinder\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\adam.GARFIELD-WIN\.conda\envs\cellfinder\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\adam.GARFIELD-WIN\.conda\envs\cellfinder\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "stringsource", line 2, in View.MemoryView._memoryviewslice.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
Processing planes:   0%|          | 0/17 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\adam.GARFIELD-WIN\.conda\envs\cellfinder\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "C:\Users\adam.GARFIELD-WIN\.conda\envs\cellfinder\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied
```

**Comment by adamltyson** [comment]
It would be good to see if someone else gets this error too.

**Comment by EmanPaoli** [comment]
Hi, I also have problems for the cell detection using Windows. The error message is:
` C:\Users\Asus>cellfinder -s C:\Users\Asus\Desktop\cellfinder_folder\signal -b C:\Users\Asus\Desktop\cellfinder_folder\anatomy -o C:\Users\Asus\Desktop\cellfinder_folder\result_cellfinder -x 1.625 -y 1.625 -z 4 --no-standard-space --soma-diameter 6 --ball-xy-size 4 --ball-z-size 4 --ball-overlap-fraction 0.4 --save-planes --no-classification
2020-04-27 12:49:13 PM - INFO - MainProcess fancylog.py:265 - Starting logging
2020-04-27 12:49:13 PM - INFO - MainProcess fancylog.py:267 - Multiprocessing-logging module found. Logging from all processes
2020-04-27 12:49:13 PM - INFO - MainProcess main.py:64 - Skipping registration
2020-04-27 12:49:13 PM - INFO - MainProcess main.py:110 - Detecting cell candidates
Processing planes:   0%|                                                                       | 0/300 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\Asus\Anaconda3\envs\cellfinderenv\Scripts\cellfinder-script.py", line 11, in <module>
    load_entry_point('cellfinder', 'console_scripts', 'cellfinder')()
  File "c:\users\asus\cellfinder\cellfinder\main.py", line 91, in main
    run_all(args, what_to_run)
  File "c:\users\asus\cellfinder\cellfinder\main.py", line 112, in run_all
    detect.main(args)
  File "c:\users\asus\cellfinder\cellfinder\detect\detect.py", line 114, in main
    bf_process.start()  # needs to be started before the loop
  File "C:\Users\Asus\Anaconda3\envs\cellfinderenv\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Asus\Anaconda3\envs\cellfinderenv\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Asus\Anaconda3\envs\cellfinderenv\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Asus\Anaconda3\envs\cellfinderenv\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Asus\Anaconda3\envs\cellfinderenv\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "stringsource", line 2, in View.MemoryView._memoryviewslice.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
Processing planes:   0%|                                                                       | 0/300 [00:00<?, ?it/s]

(cellfinderenv) C:\Users\Asus>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Asus\Anaconda3\envs\cellfinderenv\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Asus\Anaconda3\envs\cellfinderenv\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input`

**Comment by adamltyson** [comment]
Issue seems to be that the cython classes need to be pickled for multiprocessing, and the automatic method isn't working on Windows. Looks like it might need custom `__reduce__` methods

**Comment by EmanPaoli** [comment]
Yes, I came to the same conclusion. Issue seems to be solved if you create the 3 cython classes inside the process method of Mp3DFilter. I know is not an elegant solution and I just worked around the problem, but it works.

**Comment by adamltyson** [comment]
Would you mind submitting a PR?

**Comment by EmanPaoli** [comment]
sure!

**Comment by adamltyson** [comment]
Release candidate out : `pip install cellfinder==0.3.12rc0`
