### ISSUE TITLE
[BUG] Import statement in xml_crop not updated.

### ISSUE THREAD

**Issue by larsrollik** [SainsburyWellcomeCentre/cellfinder#66]
**Describe the bug**
Import broken after moving function from submodule to `imlib` package.

**To Reproduce**
Run `cellfinder_xml_crop` with standard parameters.
Current behaviour:
```
Traceback (most recent call last):
  File "/opt/anaconda/envs/cellfinder/bin/cellfinder_xml_crop", line 5, in <module>
    from cellfinder.utils.xml_crop import main
  File "/opt/anaconda/envs/cellfinder/lib/python3.7/site-packages/cellfinder/utils/xml_crop.py", line 12, in <module>
    from cellfinder.summarise.structures.structures_tree import (
ModuleNotFoundError: No module named 'cellfinder.summarise.structures'

```
**Expected behavior**
Should be:
```
from imlib.IO.structures import load_structures_as_df
```

**Comment by adamltyson** [comment]
I didn't know anyone used xml_crop. This should be fixed, can you try `pip install cellfinder==0.3.9rc0` and repeating?

**Comment by adamltyson** [comment]
@larsrollik does this work now?

**Comment by larsrollik** [comment]
Runs without problems.

**Comment by adamltyson** [comment]
Great, closing.
